# Inspiered by Daren Kitchen Hotdog-wallpaper payload
# Converted using ducky2python by CedArctic (https://github.com/CedArctic/ducky2python) 
import pyautogui
import time
time.sleep(0.1)
pyautogui.hotkey("win","r")
time.sleep(0.1)
pyautogui.typewrite("iexplore http://s3.amazonaws.com/rapgenius/hotdog.jpg", interval=0.02)
pyautogui.hotkey("enter")
time.sleep(2)
pyautogui.hotkey("alt","f")
time.sleep(0.1)
pyautogui.typewrite("a", interval=0.02)
time.sleep(0.3)
pyautogui.typewrite("hotdog.jpg", interval=0.2)
time.sleep(0.1)
pyautogui.hotkey("enter")
time.sleep(0.1)
pyautogui.hotkey("ctrl","w")
time.sleep(0.1)
pyautogui.hotkey("ctrl","esc")
time.sleep(0.1)
pyautogui.typewrite("paint", interval=0.02)
time.sleep(0.1)
pyautogui.hotkey("enter")
time.sleep(0.5)
pyautogui.hotkey("ctrl","o")
time.sleep(0.3)
pyautogui.typewrite("hotdog.jpg", interval=0.2)
pyautogui.hotkey("enter")
time.sleep(0.3)
pyautogui.hotkey("alt","f")
time.sleep(0.1)
pyautogui.typewrite("k", interval=0.02)
time.sleep(0.1)
pyautogui.typewrite("f", interval=0.02)
time.sleep(0.3)
pyautogui.hotkey("alt","f")
time.sleep(0.1)
pyautogui.typewrite("x", interval=0.02)
